name: ACR Lifecycle Policy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: AZ login
      run: | 
        az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        
    - name: Enable access to ACR
      shell: pwsh
      run: |
        chmod +x .github/scripts/enable_acr_access.ps1
        .github/scripts/enable_acr_access.ps1

    - name: Get Private Endpoint IP
      id: get-private-endpoint
      run: |
        endpoint_ip=$(az network private-endpoint show --name private-endpoint --resource-group new-rg --query "customDnsConfigs[0].ipAddresses[0]" -o tsv)
        echo "::set-output name=private_endpoint_ip::$endpoint_ip"

    

    - name: Set ACR Lifecycle Policy
      run: |
        private_endpoint_ip=${{ steps.get-private-endpoint.outputs.private_endpoint_ip }}
        acr_run_cmd="az acr run --cmd \"acr purge --filter 'prod-ww:.*' --keep 3 --ago 1m --untagged --dry-run\" --registry testsacr.azurecr.io --set DOCKER_LOGIN_SERVER=${private_endpoint_ip}"
        echo "Running ACR Lifecycle Policy with private endpoint: ${acr_run_cmd}"
        $acr_run_cmd
