name: ACR Lifecycle Policy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Enable access to ACR
      shell: pwsh
      run: |
        chmod +x .github/scripts/enable_acr_access.ps1
        .github/scripts/enable_acr_access.ps1

    - name: Set ACR Lifecycle Policy
      run: |
        az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        az acr run --cmd "acr purge --filter 'alpine:.*' --ago 10m --untagged" --registry testsacr /dev/null
