name: ACR Lifecycle Policy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set ACR Lifecycle Policy
      run: |
        az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        echo '${{ secrets.ACR_LIFECYCLE_POLICY }}' > lifecycle-policy.json
        az acr update --name ${{ secrets.ACR_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --policies @lifecycle-policy.json
